CREATE DATABASE EVENTMS;

CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    IMG_URL TEXT,
    USER_TYPE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);