-- Feature 1: Hotel Sequence
DROP SEQUENCE IF EXISTS ADD_HOTEL;

CREATE SEQUENCE ADD_HOTEL START WITH 1001 INCREMENT BY 1;

-- Feature 1: Hotel Room Sequence
DROP SEQUENCE IF EXISTS ADD_HOTEL_ROOM;

CREATE SEQUENCE ADD_HOTEL_ROOM START WITH 1 INCREMENT BY 1;

-- Feature 7: Event Reservation ID Sequence
DROP SEQUENCE IF EXISTS ADD_EVENT_RESERVATION_ID;

CREATE SEQUENCE ADD_EVENT_RESERVATION_ID START WITH 333 INCREMENT BY 111;