-- Feature 1: Hotel Sequence
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ADD_HOTEL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN -- -2289 = ORA-02289: sequence does not exist
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE ADD_HOTEL
    START WITH 1001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

-- Feature 1: Hotel Room Sequence
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ADD_HOTEL_ROOM';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE ADD_HOTEL_ROOM
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/
